apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-sauu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-sauu
    app.kubernetes.io/part-of: tkrw-pr714-0075-0001-app
  name: devfile-sample-sauu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-sauu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-sauu
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0001-tenant/tkrw-pr714-0075-0001-app/devfile-sample-sauu@sha256:42d7952685465771cb7826bfa7f522486ca3a479d7a2ed2d785eacd51061a9ba
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
